[package]
name = "mlib"
version = "0.1.0"
authors = ["Minejerik"]
license = "MIT"
description = "Minejerik's library used in all of my projects"

edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"